### ISSUE TITLE
Make esv-intersection-data compliant with equinor policies

### ISSUE THREAD

**Issue by GuillaumeVix** [equinor/esv-intersection-data#13]
## Description
[esv-intersection-data](https://github.com/equinor/esv-intersection-data) repo is related to showing the hosted [storybook](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequinor.github.io%2Fesv-intersection%2Fstorybook%2Flatest%2F%3Fpath%3D%2Fstory%2Fesv-intersection-complete-example--intersection&data=05%7C02%7CGVIX%40equinor.com%7Cef479eecec2c46c1b95108dcf1b4a4f7%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C638651005360863656%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Qu9Z%2BvPnlbfLxdSQGF3lbA6Mwfwitw2bVh11wWigmsg%3D&reserved=0) for esv-intersection.

In order to be compliant with equinor's policies, we need to move the license content into the LICENSE.md file, add a SECURITY.md, and CONTRIBUTING.md file. More info on what needs to be done in order to be compliant can be found [here](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.equinor.com%2Fgovernance%2Fscm-policy%2F&data=05%7C02%7CGVIX%40equinor.com%7Cef479eecec2c46c1b95108dcf1b4a4f7%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C638651005360889000%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=jqaJtGpMGKNA%2F8w%2BsgN%2F10s1HE7QuzPgZkFUp%2BeAbJs%3D&reserved=0).

## Acceptance criteria

1. esv-intersection-data is compliant with equinor policies
   1.1 LICENSE.md available
   1.2 SECURITY.md has been added and is up to date
   1.3 CONTRIBUTING.md file is available
2. Add scm badge (see user story https://github.com/equinor/mad-project-rep/issues/5609 for more details)
   2.1 Scm badge should be visible in the repository
   2.2 Scm badge should be green (i.e.no detected issues)

**Comment by VRiveland** [comment]
Partially fixed throuth the first PR, but we're missing a proper lisence file.

**Comment by GuillaumeVix** [comment]
@VRiveland Answer/suggestion from Andrea Brambilla:
'I suggest to take the section of the README.md file called "License" and move it to a separate License.md file.

Part of the data in that repo is taken or derived from Volve, so we either use the same license as Volve, or a compatible one (but since the Volve data is - or at least was - not a standard licence, finding a compatible one could require some work)'

=> so lets go ahead with moving the 'License' part of the Readme.md into its own License.md to be compliant with equinor guidelines.

**Comment by VRiveland** [comment]
Since the partial PR hasn't been merged yet, then I'll just be updating it and having it close the whole task. There will not be a second PR.
